"""initial_migration

Revision ID: 6dabac9fe2c8
Revises: 
Create Date: 2025-12-12 15:19:41.503288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dabac9fe2c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('properties', sa.Enum('manager', 'analyst', 'tech_spec', name='properties'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('master',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('free', 'busy', name='masterstatus'), nullable=False),
    sa.PrimaryKeyConstraint('master_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.Enum('replace', 'repair', 'maintance', name='servicetype'), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('tech_type',
    sa.Column('tech_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tech_type_id')
    )
    op.create_table('detail',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('tech_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tech_type_id'], ['tech_type.tech_type_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_addres', sa.String(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('WIP', 'completed', 'denied', name='orderstatus'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.master_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('service_detail',
    sa.Column('service_detail_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detail_id'], ['detail.detail_id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.service_id'], ),
    sa.PrimaryKeyConstraint('service_detail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_detail')
    op.drop_table('order')
    op.drop_table('detail')
    op.drop_table('tech_type')
    op.drop_table('service')
    op.drop_table('master')
    op.drop_table('admin')
    # ### end Alembic commands ###
