"""added service.name

Revision ID: 557cb81462e1
Revises: 6dabac9fe2c8
Create Date: 2026-01-29 14:12:19.112248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557cb81462e1'
down_revision: Union[str, Sequence[str], None] = '6dabac9fe2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'name')
    # ### end Alembic commands ###
